name: Build on PR

on : 
  pull_request:
      branches:
        - main

jobs:
   build:
     run-on: ubuntu-latest
     steps:
     - name: checkout repo
       uses : action/checkout@v3
     - name : Use Node.js
       uses: action/setup-node@v3
       with : 
        node-version: '20'
     - name: change directory
       run : cd frontend
     - name: install dependicies
       run : npm install
       working-directory: frontend
     - name: build
       run : npm run build

       